### ISSUE TITLE
Links to existing binders

### ISSUE THREAD

**Issue by alexanderankin** [dsibilio/spring-cloud-stream-custom-binder#1]
Currently, there are only two official binders in existence, it would really help to be able to discover those from here: https://github.com/spring-cloud/spring-cloud-stream-starters/blob/a3f6bd5bde54cd3a6d8a490a278ab4fad324dfa9/README.adoc#binder-implementations

**Comment by dsibilio** [comment]
Thanks for the feedback, added the link in the [main README references](https://github.com/dsibilio/spring-cloud-stream-custom-binder#reference-documentation).
